apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGozcHV6b2o0
  CLOUDINARY_KEY: ODk1MTUxNTQ0MTI5MzIx
  CLOUDINARY_SECRET: Q21MdkVyLVA0UlZmNzgwQUlSNVdmdWprNGlj
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lZV0prZFd4emFHRnBhekE0TVRFaUxDSmhJam9pWTIxcFpETjNaR2hvTURKa016SnZjMlkwYzJNeGJ6RnNZeUo5LlRpemoxV1FpYVQ4TTR3OUs0aGs1NlE=
  DB_URL: bW9uZ29kYitzcnY6Ly9hYmR1bHNoYWlrMDgxMV9kYl91c2VyOkw3U0RKSWNrcXF2Q3ZnMENAY2x1c3RlcjAudDg1YWM0ci5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
  SECRET: QWJkdWw=
